services:
  - type: web
    name: expense-tracker-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_SHEETS_CREDS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
